theme: jekyll-theme-cayman
title: Predicting Yelp Restaurant Ratings
description: Machine Learning (EECS 349), Northwestern University
author: Robert Luo
author_email: robertluo@u.northwestern.edu
use-site-title: true
